services:
  notebook:
    container_name: pytorch-notebook
    image: quay.io/jupyter/pytorch-notebook:cuda11-python-3.12
    ports:
      - "4040:4040"
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]
